// <auto-generated />
using System;
using Glovelly.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Glovelly.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719202048_AddTypedGigs")]
    partial class AddTypedGigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Glovelly.Api.Models.AccessRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("NotificationSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationSuppressionReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestIpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail");

                    b.HasIndex("NotificationSentAtUtc");

                    b.HasIndex("RequestedAtUtc");

                    b.ToTable("AccessRequests");
                });

            modelBuilder.Entity("Glovelly.Api.Models.CalendarSyncWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LastErrorDetail")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("LastErrorType")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingOwnerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingOwnerId");

                    b.HasIndex("GigId", "Provider");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.HasIndex("Status", "ProcessingStartedAtUtc");

                    b.HasIndex("UserId", "Provider");

                    b.ToTable("CalendarSyncWorkItems");
                });

            modelBuilder.Entity("Glovelly.Api.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("InvoiceEmailSubjectPattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InvoiceFilenamePattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("MileageRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PassengerMileageRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Glovelly.Api.Models.ExpenseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("GigExpenseId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("GigExpenseId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("ExpenseAttachments");
                });

            modelBuilder.Entity("Glovelly.Api.Models.ForScoreChart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ForScoreLibrarySnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Keywords")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PrintNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ForScoreLibrarySnapshotId");

                    b.HasIndex("ForScoreLibrarySnapshotId", "NormalizedTitle");

                    b.HasIndex("ForScoreLibrarySnapshotId", "SortOrder");

                    b.ToTable("ForScoreCharts");
                });

            modelBuilder.Entity("Glovelly.Api.Models.ForScoreLibrarySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackupVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ChartCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedByUserId", "IsActive");

                    b.ToTable("ForScoreLibrarySnapshots");
                });

            modelBuilder.Entity("Glovelly.Api.Models.Gig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("InvoicedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("PassengerCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceImportDraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TravelMiles")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("WasDriving")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("SourceImportBatchId");

                    b.HasIndex("SourceImportDraftId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Gigs");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigCalendarSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastSyncAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LastSyncHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderCalendarId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId", "Provider")
                        .IsUnique();

                    b.HasIndex("ProviderCalendarId", "ProviderEventId");

                    b.HasIndex("UserId", "Provider");

                    b.ToTable("GigCalendarSyncStates");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReimbursedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReimbursementInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReimbursementMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReimbursementNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReimbursementStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unreimbursed");

                    b.Property<DateTimeOffset?>("ReimbursementUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReimbursementUpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("ReimbursementInvoiceId");

                    b.HasIndex("ReimbursementUpdatedByUserId");

                    b.ToTable("GigExpenses");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigExternalResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.ToTable("GigExternalResources");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigExternalResourceAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("GigExternalResourceId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("GigExternalResourceId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("GigExternalResourceAttachments");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SourceFingerprint");

                    b.HasIndex("Status");

                    b.ToTable("GigImportBatches");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigImportDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccommodationNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<TimeOnly?>("ProposedArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("ProposedClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProposedClientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProposedContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ProposedContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("ProposedDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ProposedFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProposedGigType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProposedNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal?>("ProposedPerDiem")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProposedProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeOnly?>("ProposedRehearsalEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("ProposedRehearsalStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("ProposedShowEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("ProposedShowStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ProposedTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProposedVenueAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProposedVenueName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProposedVenuePostcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TravelNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ProposedClientId");

                    b.HasIndex("Status");

                    b.ToTable("GigImportDrafts");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigSetListImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GigExternalResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SpreadsheetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WorksheetId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WorksheetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GigExternalResourceId");

                    b.HasIndex("GigId");

                    b.HasIndex("GigId", "IsActive");

                    b.ToTable("GigSetListImports");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigSetListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ForScoreChartFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ForScoreChartId")
                        .HasColumnType("uuid");

                    b.Property<string>("ForScoreChartTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ForScoreLibrarySnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ForScoreMappingConfidence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("None");

                    b.Property<string>("ForScoreMappingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unmapped");

                    b.Property<DateTimeOffset?>("ForScoreMappingUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ForScoreMatchJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("GigSetListImportId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Include")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PadNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RawCellsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Section")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ForScoreChartId");

                    b.HasIndex("ForScoreLibrarySnapshotId");

                    b.HasIndex("ForScoreMappingStatus");

                    b.HasIndex("GigSetListImportId");

                    b.HasIndex("GigSetListImportId", "SortOrder");

                    b.ToTable("GigSetListItems");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GoogleCalendarIntegrationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalendarName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisconnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleCalendarId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("GoogleConnectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludeLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GoogleConnectionId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GoogleCalendarIntegrationSettings");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GoogleConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GrantedScopes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GoogleConnections");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GoogleDriveIntegrationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoogleConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvoiceUploadFolderId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GoogleConnectionId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GoogleDriveIntegrationSettings");
                });

            modelBuilder.Entity("Glovelly.Api.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DeliveryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("FirstIssuedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FirstIssuedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("LastDeliveredByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastDeliveredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastDeliveryChannel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastDeliveryRecipient")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("LastReissuedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastReissuedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PdfContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PdfFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("PdfGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PdfSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("PdfStorageKey")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("ReissueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("StatusUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PdfStorageKey")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Glovelly.Api.Models.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSystemGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("Glovelly.Api.Models.McpOAuthAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("McpOAuthAccessTokens");
                });

            modelBuilder.Entity("Glovelly.Api.Models.McpOAuthAuthorizationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CodeChallengeMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ConsumedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("ExpiresUtc");

                    b.HasIndex("UserId");

                    b.ToTable("McpOAuthAuthorizationCodes");
                });

            modelBuilder.Entity("Glovelly.Api.Models.McpOAuthRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("McpOAuthRefreshTokens");
                });

            modelBuilder.Entity("Glovelly.Api.Models.SellerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PaymentReferenceNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SellerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SortCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SellerProfiles");
                });

            modelBuilder.Entity("Glovelly.Api.Models.SetListChartMatchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SafeErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("GigId");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.HasIndex("UserId", "GigId", "CreatedAtUtc");

                    b.ToTable("SetListChartMatchJobs");
                });

            modelBuilder.Entity("Glovelly.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultPaymentWindowDays")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("InvoiceEmailBodyTemplate")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("InvoiceEmailSubjectPattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InvoiceFilenamePattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InvoiceReplyToEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MileageRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("PassengerMileageRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TravelOriginPostcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Glovelly.Api.Models.CalendarSyncWorkItem", b =>
                {
                    b.HasOne("Glovelly.Api.Models.User", "User")
                        .WithMany("CalendarSyncWorkItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Glovelly.Api.Models.Client", b =>
                {
                    b.HasOne("Glovelly.Api.Models.User", "CreatedByUser")
                        .WithMany("ClientsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Glovelly.Api.Models.User", "UpdatedByUser")
                        .WithMany("ClientsUpdated")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Glovelly.Api.Models.Address", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("StateOrCounty")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Glovelly.Api.Models.ExpenseAttachment", b =>
                {
                    b.HasOne("Glovelly.Api.Models.GigExpense", "Expense")
                        .WithMany("Attachments")
                        .HasForeignKey("GigExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("Glovelly.Api.Models.ForScoreChart", b =>
                {
                    b.HasOne("Glovelly.Api.Models.ForScoreLibrarySnapshot", "Snapshot")
                        .WithMany("Charts")
                        .HasForeignKey("ForScoreLibrarySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Glovelly.Api.Models.ForScoreLibrarySnapshot", b =>
                {
                    b.HasOne("Glovelly.Api.Models.User", "CreatedByUser")
                        .WithMany("ForScoreLibrarySnapshots")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Glovelly.Api.Models.Gig", b =>
                {
                    b.HasOne("Glovelly.Api.Models.Client", "Client")
                        .WithMany("Gigs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Glovelly.Api.Models.User", "CreatedByUser")
                        .WithMany("GigsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Glovelly.Api.Models.Invoice", "Invoice")
                        .WithMany("Gigs")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Glovelly.Api.Models.GigImportBatch", "SourceImportBatch")
                        .WithMany()
                        .HasForeignKey("SourceImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Glovelly.Api.Models.GigImportDraft", "SourceImportDraft")
                        .WithMany()
                        .HasForeignKey("SourceImportDraftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Glovelly.Api.Models.User", "UpdatedByUser")
                        .WithMany("GigsUpdated")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Invoice");

                    b.Navigation("SourceImportBatch");

                    b.Navigation("SourceImportDraft");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigCalendarSyncState", b =>
                {
                    b.HasOne("Glovelly.Api.Models.User", "User")
                        .WithMany("GigCalendarSyncStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigExpense", b =>
                {
                    b.HasOne("Glovelly.Api.Models.Gig", "Gig")
                        .WithMany("Expenses")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glovelly.Api.Models.Invoice", "ReimbursementInvoice")
                        .WithMany()
                        .HasForeignKey("ReimbursementInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Glovelly.Api.Models.User", "ReimbursementUpdatedByUser")
                        .WithMany()
                        .HasForeignKey("ReimbursementUpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gig");

                    b.Navigation("ReimbursementInvoice");

                    b.Navigation("ReimbursementUpdatedByUser");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigExternalResource", b =>
                {
                    b.HasOne("Glovelly.Api.Models.Gig", "Gig")
                        .WithMany("ExternalResources")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigExternalResourceAttachment", b =>
                {
                    b.HasOne("Glovelly.Api.Models.GigExternalResource", "Resource")
                        .WithMany("Attachments")
                        .HasForeignKey("GigExternalResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigImportBatch", b =>
                {
                    b.HasOne("Glovelly.Api.Models.User", "CreatedByUser")
                        .WithMany("GigImportBatchesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigImportDraft", b =>
                {
                    b.HasOne("Glovelly.Api.Models.GigImportBatch", "Batch")
                        .WithMany("Drafts")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glovelly.Api.Models.Client", "ProposedClient")
                        .WithMany()
                        .HasForeignKey("ProposedClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batch");

                    b.Navigation("ProposedClient");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigSetListImport", b =>
                {
                    b.HasOne("Glovelly.Api.Models.GigExternalResource", "GigExternalResource")
                        .WithMany()
                        .HasForeignKey("GigExternalResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Glovelly.Api.Models.Gig", "Gig")
                        .WithMany("SetListImports")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("GigExternalResource");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigSetListItem", b =>
                {
                    b.HasOne("Glovelly.Api.Models.ForScoreChart", "ForScoreChart")
                        .WithMany()
                        .HasForeignKey("ForScoreChartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Glovelly.Api.Models.ForScoreLibrarySnapshot", "ForScoreLibrarySnapshot")
                        .WithMany()
                        .HasForeignKey("ForScoreLibrarySnapshotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Glovelly.Api.Models.GigSetListImport", "Import")
                        .WithMany("Items")
                        .HasForeignKey("GigSetListImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForScoreChart");

                    b.Navigation("ForScoreLibrarySnapshot");

                    b.Navigation("Import");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GoogleCalendarIntegrationSettings", b =>
                {
                    b.HasOne("Glovelly.Api.Models.GoogleConnection", "GoogleConnection")
                        .WithOne("CalendarSettings")
                        .HasForeignKey("Glovelly.Api.Models.GoogleCalendarIntegrationSettings", "GoogleConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glovelly.Api.Models.User", "User")
                        .WithOne("GoogleCalendarIntegrationSettings")
                        .HasForeignKey("Glovelly.Api.Models.GoogleCalendarIntegrationSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoogleConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GoogleConnection", b =>
                {
                    b.HasOne("Glovelly.Api.Models.User", "User")
                        .WithOne("GoogleConnection")
                        .HasForeignKey("Glovelly.Api.Models.GoogleConnection", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GoogleDriveIntegrationSettings", b =>
                {
                    b.HasOne("Glovelly.Api.Models.GoogleConnection", "GoogleConnection")
                        .WithOne("DriveSettings")
                        .HasForeignKey("Glovelly.Api.Models.GoogleDriveIntegrationSettings", "GoogleConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glovelly.Api.Models.User", "User")
                        .WithOne("GoogleDriveIntegrationSettings")
                        .HasForeignKey("Glovelly.Api.Models.GoogleDriveIntegrationSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoogleConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Glovelly.Api.Models.Invoice", b =>
                {
                    b.HasOne("Glovelly.Api.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Glovelly.Api.Models.User", "CreatedByUser")
                        .WithMany("InvoicesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Glovelly.Api.Models.User", "UpdatedByUser")
                        .WithMany("InvoicesUpdated")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Glovelly.Api.Models.InvoiceLine", b =>
                {
                    b.HasOne("Glovelly.Api.Models.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Glovelly.Api.Models.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Glovelly.Api.Models.McpOAuthAccessToken", b =>
                {
                    b.HasOne("Glovelly.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Glovelly.Api.Models.McpOAuthAuthorizationCode", b =>
                {
                    b.HasOne("Glovelly.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Glovelly.Api.Models.McpOAuthRefreshToken", b =>
                {
                    b.HasOne("Glovelly.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Glovelly.Api.Models.SellerProfile", b =>
                {
                    b.HasOne("Glovelly.Api.Models.User", "CreatedByUser")
                        .WithMany("SellerProfilesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Glovelly.Api.Models.User", "UpdatedByUser")
                        .WithMany("SellerProfilesUpdated")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Glovelly.Api.Models.User", "User")
                        .WithOne("SellerProfile")
                        .HasForeignKey("Glovelly.Api.Models.SellerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Glovelly.Api.Models.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("SellerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Line1")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("StateOrCounty")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("SellerProfileId");

                            b1.ToTable("SellerProfiles");

                            b1.WithOwner()
                                .HasForeignKey("SellerProfileId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Glovelly.Api.Models.SetListChartMatchJob", b =>
                {
                    b.HasOne("Glovelly.Api.Models.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glovelly.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Glovelly.Api.Models.Client", b =>
                {
                    b.Navigation("Gigs");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Glovelly.Api.Models.ForScoreLibrarySnapshot", b =>
                {
                    b.Navigation("Charts");
                });

            modelBuilder.Entity("Glovelly.Api.Models.Gig", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("ExternalResources");

                    b.Navigation("SetListImports");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigExpense", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigExternalResource", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigImportBatch", b =>
                {
                    b.Navigation("Drafts");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GigSetListImport", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Glovelly.Api.Models.GoogleConnection", b =>
                {
                    b.Navigation("CalendarSettings");

                    b.Navigation("DriveSettings");
                });

            modelBuilder.Entity("Glovelly.Api.Models.Invoice", b =>
                {
                    b.Navigation("Gigs");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Glovelly.Api.Models.User", b =>
                {
                    b.Navigation("CalendarSyncWorkItems");

                    b.Navigation("ClientsCreated");

                    b.Navigation("ClientsUpdated");

                    b.Navigation("ForScoreLibrarySnapshots");

                    b.Navigation("GigCalendarSyncStates");

                    b.Navigation("GigImportBatchesCreated");

                    b.Navigation("GigsCreated");

                    b.Navigation("GigsUpdated");

                    b.Navigation("GoogleCalendarIntegrationSettings");

                    b.Navigation("GoogleConnection");

                    b.Navigation("GoogleDriveIntegrationSettings");

                    b.Navigation("InvoicesCreated");

                    b.Navigation("InvoicesUpdated");

                    b.Navigation("SellerProfile");

                    b.Navigation("SellerProfilesCreated");

                    b.Navigation("SellerProfilesUpdated");
                });
#pragma warning restore 612, 618
        }
    }
}
